import json
import math
from datetime import datetime

import faker

author_list = [
    {"name": "Jeffrey Wells", "email": "rmorris@example.net"},
    {"name": "Kenneth Hunter", "email": "eguerrero@example.net"},
    {"name": "Rachel Jackson", "email": "tiffany20@example.org"},
    {"name": "Kathleen Harris", "email": "levi12@example.org"},
    {"name": "William Duran", "email": "ashleycardenas@example.net"},
    {"name": "Eric Ball", "email": "rodriguezgabriela@example.com"},
    {"name": "Carlos Todd", "email": "kevin32@example.com"},
    {"name": "Victor Valentine", "email": "seanmartinez@example.org"},
    {"name": "Henry Barnett", "email": "schroederbailey@example.com"},
    {"name": "Joseph Hall", "email": "wilkinsleonard@example.net"},
    {"name": "Jessica Allen", "email": "david11@example.org"},
    {"name": "Christopher Brown", "email": "phyllis66@example.org"},
    {"name": "Laurie Guerrero", "email": "timothytate@example.org"},
    {"name": "Leah Phillips", "email": "michelle95@example.net"},
    {"name": "Andrew Brown", "email": "patricia67@example.com"},
    {"name": "Miss Theresa Nelson", "email": "xcarter@example.net"},
    {"name": "Rachel Werner", "email": "leslie08@example.com"},
    {"name": "Andrew Briggs", "email": "alexander26@example.com"},
    {"name": "Colleen Kelly", "email": "erin22@example.com"},
    {"name": "Deanna Roberts", "email": "qpena@example.org"},
]
outliers_list = [
    {
        "sha": "yncVBcrQsStRJRGdlbYo",
        "message": "Throughout toward fact need that.",
        "additions": 3939,
        "deletions": 508,
        "deviation_score": 2.41,
        "author": {"name": "Andrew Briggs", "email": "tiffany20@example.org"},
        "date": "2025-06-27T18:20:07.170909",
    },
    {
        "sha": "hoCaEVNBaIeOXpod",
        "message": "Seat early notice fight.",
        "additions": 2773,
        "deletions": 776,
        "deviation_score": 2.21,
        "author": {"name": "Joseph Hall", "email": "patricia67@example.com"},
        "date": "2025-05-22T04:40:49.877124",
    },
    {
        "sha": "lKywIACWgmNuMmOc",
        "message": "Program month soldier memory rate.",
        "additions": 3208,
        "deletions": 549,
        "deviation_score": 2.33,
        "author": {"name": "Colleen Kelly", "email": "leslie08@example.com"},
        "date": "2025-01-03T06:44:13.300699",
    },
    {
        "sha": "HuLlVnQAixbnSIWQ",
        "message": "Girl he series itself senior five region.",
        "additions": 1341,
        "deletions": 856,
        "deviation_score": 3.16,
        "author": {"name": "Eric Ball", "email": "schroederbailey@example.com"},
        "date": "2025-07-12T01:14:34.197133",
    },
    {
        "sha": "bemWDafBMKvyULeOwx",
        "message": "Police general across parent.",
        "additions": 4107,
        "deletions": 465,
        "deviation_score": 3.93,
        "author": {"name": "William Duran", "email": "patricia67@example.com"},
        "date": "2025-06-19T09:43:23.725627",
    },
    {
        "sha": "tIlKcGBbJEBQVSuksbs",
        "message": "Range respond use imagine issue.",
        "additions": 3530,
        "deletions": 278,
        "deviation_score": 3.29,
        "author": {"name": "Jessica Allen", "email": "patricia67@example.com"},
        "date": "2025-05-09T16:24:22.188208",
    },
    {
        "sha": "HqYDWaooYJHBKIqd",
        "message": "Expert north who yeah.",
        "additions": 2676,
        "deletions": 247,
        "deviation_score": 2.7,
        "author": {"name": "Jeffrey Wells", "email": "xcarter@example.net"},
        "date": "2025-06-25T06:24:15.764061",
    },
    {
        "sha": "ffGOoemGWAVrAJVFBZT",
        "message": "Let quality break garden get clearly sing.",
        "additions": 2128,
        "deletions": 468,
        "deviation_score": 3.72,
        "author": {"name": "Eric Ball", "email": "erin22@example.com"},
        "date": "2025-02-12T03:39:56.487789",
    },
    {
        "sha": "OznwtHQzEtqaReFuO",
        "message": "Would now save blue key during.",
        "additions": 4849,
        "deletions": 898,
        "deviation_score": 3.47,
        "author": {"name": "Henry Barnett", "email": "michelle95@example.net"},
        "date": "2025-05-23T11:55:12.530906",
    },
    {
        "sha": "UqaDOmFxhrXSZFeM",
        "message": "Shake establish conference cold.",
        "additions": 3802,
        "deletions": 438,
        "deviation_score": 3.26,
        "author": {"name": "Victor Valentine", "email": "eguerrero@example.net"},
        "date": "2025-01-15T19:04:01.101248",
    },
    {
        "sha": "NajhhUYMPBbFcTRcX",
        "message": "Computer I Mr huge.",
        "additions": 2928,
        "deletions": 307,
        "deviation_score": 3.2,
        "author": {"name": "Leah Phillips", "email": "michelle95@example.net"},
        "date": "2025-05-24T13:28:17.425988",
    },
    {
        "sha": "hljDnjIoQqVJXsgNwXP",
        "message": "Customer growth build.",
        "additions": 4324,
        "deletions": 210,
        "deviation_score": 3.1,
        "author": {"name": "Joseph Hall", "email": "erin22@example.com"},
        "date": "2025-06-01T07:48:51.592946",
    },
    {
        "sha": "ydIVPxMufRtLULSO",
        "message": "Everything least citizen popular defense.",
        "additions": 4288,
        "deletions": 394,
        "deviation_score": 2.99,
        "author": {"name": "Victor Valentine", "email": "levi12@example.org"},
        "date": "2025-04-19T16:50:40.628879",
    },
    {
        "sha": "XjbWYDqGkabRtSVAGcx",
        "message": "All real marriage event.",
        "additions": 2058,
        "deletions": 160,
        "deviation_score": 2.6,
        "author": {"name": "Andrew Brown", "email": "xcarter@example.net"},
        "date": "2025-03-26T18:01:18.280982",
    },
    {
        "sha": "nBhxnnpIVveFiqTsz",
        "message": "Fact foreign explain discover analysis agent by return.",
        "additions": 1409,
        "deletions": 468,
        "deviation_score": 2.41,
        "author": {"name": "Miss Theresa Nelson", "email": "rmorris@example.net"},
        "date": "2025-03-17T22:53:10.085358",
    },
    {
        "sha": "wHCtHSWSrIHCQGJo",
        "message": "Make whether cost travel may number wide member.",
        "additions": 3300,
        "deletions": 416,
        "deviation_score": 3.54,
        "author": {"name": "Carlos Todd", "email": "rodriguezgabriela@example.com"},
        "date": "2025-03-28T01:03:27.988366",
    },
    {
        "sha": "jGMAxbKXDsTxlAicuH",
        "message": "Can visit energy oil throughout.",
        "additions": 4721,
        "deletions": 781,
        "deviation_score": 2.49,
        "author": {"name": "Miss Theresa Nelson", "email": "leslie08@example.com"},
        "date": "2025-05-28T00:34:42.421608",
    },
    {
        "sha": "WlmUACiQnOYUxpyuaWq",
        "message": "Approach claim energy have democratic field pressure.",
        "additions": 3542,
        "deletions": 767,
        "deviation_score": 2.33,
        "author": {"name": "Christopher Brown", "email": "seanmartinez@example.org"},
        "date": "2025-04-27T12:31:33.173287",
    },
    {
        "sha": "WVUVsasNlEKAnMDVM",
        "message": "Control PM you.",
        "additions": 4052,
        "deletions": 252,
        "deviation_score": 3.33,
        "author": {"name": "Christopher Brown", "email": "schroederbailey@example.com"},
        "date": "2025-02-27T19:28:58.910168",
    },
    {
        "sha": "fOxgEvAfcGIqMhfQXnEr",
        "message": "Crime all build note garden effort nor.",
        "additions": 4449,
        "deletions": 389,
        "deviation_score": 2.69,
        "author": {"name": "William Duran", "email": "leslie08@example.com"},
        "date": "2025-04-28T13:35:32.984368",
    },
    {
        "sha": "dCLCTGhTsHbLDXqu",
        "message": "Authority up teacher law director thank rather.",
        "additions": 1457,
        "deletions": 734,
        "deviation_score": 2.93,
        "author": {"name": "William Duran", "email": "wilkinsleonard@example.net"},
        "date": "2025-07-08T22:45:28.232161",
    },
    {
        "sha": "qCtfdltBThqoKKPY",
        "message": "Main page travel street military.",
        "additions": 3718,
        "deletions": 130,
        "deviation_score": 2.34,
        "author": {"name": "Laurie Guerrero", "email": "leslie08@example.com"},
        "date": "2025-01-13T02:19:45.754785",
    },
    {
        "sha": "uhehZgMLJKhjnLzi",
        "message": "Firm responsibility sign.",
        "additions": 2172,
        "deletions": 284,
        "deviation_score": 3.54,
        "author": {"name": "Leah Phillips", "email": "wilkinsleonard@example.net"},
        "date": "2025-01-01T10:35:31.212787",
    },
    {
        "sha": "lHeOKejfnUjGKDvxJF",
        "message": "Future despite more arm report boy.",
        "additions": 3548,
        "deletions": 862,
        "deviation_score": 3.49,
        "author": {"name": "Victor Valentine", "email": "ashleycardenas@example.net"},
        "date": "2025-07-01T22:35:23.037731",
    },
    {
        "sha": "STtxIcDiXmqFNejZRt",
        "message": "Which section begin discuss sister shoulder.",
        "additions": 3495,
        "deletions": 918,
        "deviation_score": 2.74,
        "author": {"name": "William Duran", "email": "kevin32@example.com"},
        "date": "2025-05-22T00:03:52.689117",
    },
    {
        "sha": "kYgxUolQJYlvPDmWJA",
        "message": "Production left cultural owner others present give.",
        "additions": 4444,
        "deletions": 571,
        "deviation_score": 3.78,
        "author": {"name": "Rachel Werner", "email": "timothytate@example.org"},
        "date": "2025-01-13T07:14:55.986438",
    },
    {
        "sha": "RCuTbyjPxwTkkYapMzB",
        "message": "Sort subject reflect business human state thus.",
        "additions": 4884,
        "deletions": 132,
        "deviation_score": 3.62,
        "author": {"name": "Miss Theresa Nelson", "email": "alexander26@example.com"},
        "date": "2025-06-04T01:39:46.359677",
    },
    {
        "sha": "lXTIGiNqXolIlYCmqkz",
        "message": "Such get people.",
        "additions": 3396,
        "deletions": 688,
        "deviation_score": 3.62,
        "author": {"name": "Carlos Todd", "email": "kevin32@example.com"},
        "date": "2025-01-28T11:06:40.889958",
    },
    {
        "sha": "mYZLyGotHjNdGYRAyRPF",
        "message": "I together some without.",
        "additions": 4675,
        "deletions": 523,
        "deviation_score": 2.29,
        "author": {"name": "Rachel Werner", "email": "schroederbailey@example.com"},
        "date": "2025-04-08T11:29:15.491133",
    },
    {
        "sha": "YWRlMaPKnjHpmKcZbDK",
        "message": "Away you fund each.",
        "additions": 4079,
        "deletions": 580,
        "deviation_score": 2.12,
        "author": {"name": "Joseph Hall", "email": "wilkinsleonard@example.net"},
        "date": "2025-05-22T04:15:57.928364",
    },
    {
        "sha": "iTyEqkPruKZraIGoqS",
        "message": "Run trade hand Mr subject.",
        "additions": 2525,
        "deletions": 416,
        "deviation_score": 2.78,
        "author": {"name": "Laurie Guerrero", "email": "schroederbailey@example.com"},
        "date": "2025-06-26T03:16:43.386222",
    },
    {
        "sha": "gTetOPosJvnufVXLjTKx",
        "message": "Because tonight feeling stock check.",
        "additions": 2598,
        "deletions": 318,
        "deviation_score": 2.5,
        "author": {"name": "Andrew Briggs", "email": "seanmartinez@example.org"},
        "date": "2025-02-26T10:39:35.280275",
    },
    {
        "sha": "VLUjRCwHmuYOhVINCsIR",
        "message": "Character lead build none.",
        "additions": 2344,
        "deletions": 121,
        "deviation_score": 3.7,
        "author": {"name": "Jeffrey Wells", "email": "patricia67@example.com"},
        "date": "2025-04-11T02:51:29.989958",
    },
    {
        "sha": "hFiMXbVFHnhDrMlTVd",
        "message": "Week yard conference worry just spring computer.",
        "additions": 1456,
        "deletions": 811,
        "deviation_score": 2.39,
        "author": {"name": "Eric Ball", "email": "timothytate@example.org"},
        "date": "2025-06-05T22:29:02.061898",
    },
    {
        "sha": "CIBNHevEQwtWZpGgN",
        "message": "Yourself deep day event mention voice.",
        "additions": 2449,
        "deletions": 384,
        "deviation_score": 3.75,
        "author": {"name": "Andrew Brown", "email": "levi12@example.org"},
        "date": "2025-03-02T12:20:50.475540",
    },
    {
        "sha": "KZqqEHTHpfkeiAFuWWa",
        "message": "Size agent else.",
        "additions": 4600,
        "deletions": 943,
        "deviation_score": 3.75,
        "author": {"name": "William Duran", "email": "xcarter@example.net"},
        "date": "2025-06-16T11:57:16.429276",
    },
    {
        "sha": "rIdVwNtCuttIgkRWAkw",
        "message": "Along although ground.",
        "additions": 4028,
        "deletions": 206,
        "deviation_score": 2.1,
        "author": {"name": "Miss Theresa Nelson", "email": "timothytate@example.org"},
        "date": "2025-07-05T18:56:24.369381",
    },
    {
        "sha": "VceUHtJGPdUJFKbtzZe",
        "message": "Bill within education policy.",
        "additions": 4766,
        "deletions": 681,
        "deviation_score": 3.35,
        "author": {
            "name": "Christopher Brown",
            "email": "rodriguezgabriela@example.com",
        },
        "date": "2025-03-11T08:11:15.756535",
    },
    {
        "sha": "WVplrEISiozVaIkuUX",
        "message": "Example court offer generation onto.",
        "additions": 2162,
        "deletions": 716,
        "deviation_score": 2.5,
        "author": {"name": "Henry Barnett", "email": "eguerrero@example.net"},
        "date": "2025-05-01T16:30:20.785731",
    },
    {
        "sha": "WHvhqqaljTqYjdkn",
        "message": "Ground style beat.",
        "additions": 1404,
        "deletions": 429,
        "deviation_score": 3.14,
        "author": {"name": "Jessica Allen", "email": "patricia67@example.com"},
        "date": "2025-04-04T19:07:15.273919",
    },
    {
        "sha": "JeKrjtxWYPBQCKUb",
        "message": "Watch value stay idea character themselves.",
        "additions": 4165,
        "deletions": 843,
        "deviation_score": 2.12,
        "author": {"name": "Carlos Todd", "email": "ashleycardenas@example.net"},
        "date": "2025-02-02T04:16:59.802958",
    },
    {
        "sha": "jVmvXbXcPlnZpHRWcUMd",
        "message": "All daughter simple seat write.",
        "additions": 3720,
        "deletions": 818,
        "deviation_score": 2.7,
        "author": {"name": "Henry Barnett", "email": "ashleycardenas@example.net"},
        "date": "2025-05-15T22:00:40.124837",
    },
    {
        "sha": "nEETEMpiatZedbCSpYI",
        "message": "Address reveal perform certainly often wear.",
        "additions": 1594,
        "deletions": 879,
        "deviation_score": 3.72,
        "author": {"name": "Eric Ball", "email": "rodriguezgabriela@example.com"},
        "date": "2025-01-08T02:31:46.973760",
    },
    {
        "sha": "hyowaIhVykSquiJlB",
        "message": "Page data life night one they street.",
        "additions": 1623,
        "deletions": 204,
        "deviation_score": 3.32,
        "author": {"name": "Deanna Roberts", "email": "rmorris@example.net"},
        "date": "2025-03-12T03:16:05.427303",
    },
    {
        "sha": "XqiZFjPVHeDtfJWhQj",
        "message": "Ago term born father keep.",
        "additions": 3064,
        "deletions": 953,
        "deviation_score": 2.26,
        "author": {"name": "Jeffrey Wells", "email": "phyllis66@example.org"},
        "date": "2025-01-24T22:31:45.454206",
    },
    {
        "sha": "xXLErFDCdgILsebUCSfY",
        "message": "To view relate push.",
        "additions": 1743,
        "deletions": 783,
        "deviation_score": 2.1,
        "author": {"name": "Laurie Guerrero", "email": "seanmartinez@example.org"},
        "date": "2025-03-26T04:05:49.967901",
    },
    {
        "sha": "RnusJocvoWppYHHd",
        "message": "While left two.",
        "additions": 4215,
        "deletions": 951,
        "deviation_score": 2.18,
        "author": {"name": "Eric Ball", "email": "rodriguezgabriela@example.com"},
        "date": "2025-05-10T19:02:11.025855",
    },
    {
        "sha": "EJBMuJgmGjSlCwiemDaP",
        "message": "Ask ability walk star become hit.",
        "additions": 2018,
        "deletions": 905,
        "deviation_score": 3.58,
        "author": {"name": "Rachel Jackson", "email": "alexander26@example.com"},
        "date": "2025-04-27T20:04:13.816759",
    },
    {
        "sha": "JleARVIfbrBqqNIGxw",
        "message": "Face like about design gas series edge.",
        "additions": 2573,
        "deletions": 225,
        "deviation_score": 3.78,
        "author": {"name": "Jeffrey Wells", "email": "schroederbailey@example.com"},
        "date": "2025-05-09T05:35:22.408870",
    },
    {
        "sha": "UgqftRhIKcaRAhkcqEdt",
        "message": "Actually less finally step quickly military fear.",
        "additions": 4460,
        "deletions": 554,
        "deviation_score": 3.32,
        "author": {"name": "Laurie Guerrero", "email": "michelle95@example.net"},
        "date": "2025-03-02T21:34:04.390796",
    },
]


class GithubService:
    def __init__(self):
        self.base_url = "https://api.github.com/graphql"
        self.token = "TEST_VALUE"
        self.headers = {
            "Authorization": f"Bearer {self.token}",
        }

    def fetch_authors_stub(self):
        return author_list

    def fetch_outliers_stub(self):
        return json.loads(json.dumps(outliers_list))

    def fetch_word_cloud_stub(self):
        return [
            {
                "word": faker.Faker().word(),
                "count": faker.Faker().pyint(
                    min_value=math.floor(math.log(math.fabs(x - 10) + 1) + 1),
                    max_value=10,
                ),
            }
            for x in range(30)
        ]

    def search_outliers(self, start_date, end_date):
        outliers_list = self.fetch_outliers_stub()

        filtered_outliers = [
            outlier
            for outlier in outliers_list
            if start_date <= datetime.fromisoformat(outlier["date"]) <= end_date
        ]

        return filtered_outliers
